### ISSUE TITLE
[META] phase 2

### ISSUE THREAD

**Issue by oliverklee** [phpList/web-frontend#16]
This meta ticket covers the web-frontend-related tasks for phase 2. The core-specific tasks are listed in https://github.com/phpList/phplist4-core/issues/125, the base-distribution-specific tasks are listed in https://github.com/phpList/base-distribution/issues/18, and the rest-api-specific tasks are listed in https://github.com/phpList/rest-api/issues/20.

- [x] make sure Composer installs the latest version of the dependencies (should be fixed as this was a Packagist configuration issue)
- [x] rename the branch alias from 4.0.0-dev to 4.0.x-dev https://getcomposer.org/doc/articles/aliases.md#branch-alias
- [x] #18 use the bin/ and web/ generation script from the core
